name: README构建

on:
  push:
    branches: [ "master","main"]
    
jobs:
  Build:
    runs-on: windows-latest
    name: 初始化
    steps:
      - uses: actions/checkout@v4
      - name: 下载
        shell: powershell
        run: |
         $ProgressPreference = 'SilentlyContinue'
         Invoke-WebRequest -Uri https://github.com/CrazyMayfly/Free-Markdown-Translator/releases/download/1.2/MarkdownTranslator.v1.2.zip -OutFile "MarkdownTranslator.zip"
         Expand-Archive -Path ./MarkdownTranslator.zip -DestinationPath MarkdownTranslator
